pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'Ornithe Releases'
			url = 'https://maven.ornithemc.net/releases'
		}
		maven {
			name = 'Ornithe Snapshots'
			url = 'https://maven.ornithemc.net/snapshots'
		}
		mavenLocal()
		gradlePluginPortal()
	}
}

rootProject.name = "LoadZone"
include 'versions:inf624'
include 'versions:b1.2_02-20110517'
