# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=b1.2_02-20110517
loader_version=0.16.0

# Mod Properties
version=1.1.1
maven_group=me.dexrn
archives_base_name=loadzone

# Not obfuscated!
fabric.loom.dontRemap=true
fabric.loom.disableObfuscation=true
