# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
version = 1.1.1
maven_group = me.dexrn
archives_base_name = LoadZone

# Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version = inf-20100624
loader_version = 0.19.5

nests_build = 3
feather_build = 2

osl_version = 0.21.0
